# -*- coding: utf-8 -*-
"""CSE111 basics practise Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yCcqy49qUtIzjsc6IOLc1rMjTTVuTmve
"""

Var='Hello This is Tasrif Coding'
print(Var)    #So variable can have captial letter or small letter it doesn't matter but built in function must have small letters otherwise it won't work.

"""CSE110 Recap"""

list1=[10,20,30,40,50]
list2=[40,50,60,70,80]

index=0
while index<len(list1):           #Counts character by addressign their index at first
    print(list1[index])
    index+=1

for i in range(0,len(list1),1):      #Counts character by addressing their index at first
    print(list1[i])

for i in list1:          #Counts directly their character everytime
    print(i)

a_tuple=(10, 'Md Tasrif Khan', 10)
print(a_tuple)
a_list=list(a_tuple)
print(a_list)

Var=''



"""Python OOP (Object Oriented Programming)"""

class Employ:
    #paramiterized constructor
    def __init__(self, name, no):
        self.no=no    #instance variable
        self.name=name    #instance variable
    #Instance method
    def display(self):
        print(self.name, self.no)
emp1=Employ('Jhon',11)    #Instance 1
emp2=Employ('David',12)    #Instance 2
emp1.display()
emp2.display()

"""Class Object Constructor Attributes:"""

class student:
    def __init__(self):
        print(self)
        print('a student object created')
#varibale =class_name()
s1=student()
s2=student()
print('S1',s1)

class student:
    def __init__(self, name, ID):
        self.name= name    #Instance variable
        self.id= ID    #Instance variable
        #print('a student object created)
        
#variable=class_name()
s1=student('BOb',11)
s2=student('Carol',22)
print(s1,id)    #11
s1.id=33
print(s2.id)
print(s2.name)

class student:
    def __init__(self, name, ID):
        self.name= name    #Instance variable
        self.id= ID    #Instance variable
        #print('a student object created)
    def details(self):
        print('Name:',self.name, "ID", self.id)

#variable=class_name()
s1=student('Bob',11)
s2=student('Carol',22)
print(s1,id)    #11
s1.id=33
s2.name= 'David'
print(s2.id)
print(s2.name)
s1.details()
s2.details()

name=input('Sir, please enter your desired number: ')
add=''
a_list=[]
new_list=[]
for i in range(len(name)):
    if name[i]==' ':
        pass
    else: 
        a_list.append(name[i])
print(a_list)
for j in a_list:
    if j not in new_list:
        new_list.append(j)
print(new_list)

var='Hello People'
a_list=[]
for i in range(len(var)):
    if var[i]=='l':
        a_list.append(var[i])
print(a_list)

"""Dictionary"""

d1={'Key1':'Value1', 2: 'minus value', 2.5: 'Value2', (1,2):'hi'}
print(d1)

p1={'name':'Sakib Al Hasan', 'Country':'BD','Age':35}
p2={'name':'Brad pitt', 'Country':'USA','Age':60}
p3={'name':'Ananta Jalil', 'Country': 'BD', 'Age': 44}

actor={'BD':[p1,p3], 'USA':p2}
print(actor)
print(actor['BD'])
print(actor['BD'][1])

dt={'Name':'Zara','Age': 7, 'Class':'First'}
print(dt)
dt['Age']=8    #Update existing entry
dt['School']= 'DPS School'    #Add new entry
print(dt)
del dt['Name']    #remove entry with key 'Name'
print(dt)
# dt.clear()    #remove all entries in dict
# print(dt)
#del dt    #Delete entire dictionary
print(dt)
pop_ele=dt.pop('Class')
print('After operation')
print(dt)
print(pop_ele)

d1={1:10, 2:4}
d2=dict({1:2, 4:5})
print(d2)
d3=dict([('v1','k1'), ('k2','v2'),('k3','v3')])
print(d3)

"""CSE111 Assignment"""

#task-1:
name=str(input('Sir, please enter your desired word: '))
upper_count=0
lower_count=0
for i in range(len(name)):
    if 65<=ord(name[i])<=90:
        upper_count+=1
    else:
         lower_count+=1
print(upper_count)
print(lower_count)

var=''
if upper_count<lower_count:
    var=name.lower()
else:
    var=name.upper()
print(var)

#task-2:
word=input('Sir, please enter your desired word: ')
string=0
number=0
for i in range(len(word)):
    if 48<=ord(word[i])<=57:
        number+=1      
    elif 65<=ord(word[i])<=90 or 97<=ord(word[i])<=122:
        string+=1
print(number)   
print(string)    

if string==len(word):
    print('WORD')
elif number== len(word):
    print('NUMBER')
else:
    print('MIXED')

#task-3:
word=input('Sir, please enter your word: ')
var=[]

for i in range(len(word)):
    if 65<=ord(word[i])<=90:
        var.append(i)

print(var)

new=word[var[0]+1 : var[1]]
if len(new)>0:
    print(new)
else:
    print('BLANK')

#task-4:
word=input('Sir, please enter your desired word: ')
new_list=[]
for j in word:
    if j not in new_list:
            new_list.append(j)
print(new_list)
b_list=[]
for i in new_list:
    if i==' ' or i==',':
        pass
    else:
        b_list.append(i)
print(b_list)
var=''
print(var)

sample=input("Enter two words using comma: ")

sample=sample.split(",")
print(sample)
value_1=sample[0]
print(value_1)
value_2=sample[1]
final=""

for i in range(len(value_1)):
  if value_1[i] in value_2:
      final+=value_1[i]
for j in range(len(value_2)):
  if value_2[j] in value_1:
      final+=value_2[j]

if len(final)==0:
  print("Nothing in common")
else:
   print(final)

word=input()
var=''
for i in word:
    if i not in var:
        pass
    else:
        var=var+i
    
print(var)

#task-5:
word=input('Sir, please insert your desired credentials: ')
digit=0
upper=0
lower=0
for i in word:
    if 48<=ord(i)<=57:
        digit+=1
    elif 65<=ord(i)<=90:
        upper+=1
    else:
        lower+=1
    
print(digit)
if upper==0 or lower==0 or digit==0:
    print('Uppercase character missing. Digit missing. Special character missing')
elif digit==0:
    print('Digit Missing')
else:
    print('OK')

"""List of assignment-1:"""

#task-1:
number=int(input('Sir, please enter your number: '))
num1=0
num2=0
num3=0
num4=0
num5=0
a_list=[]
for i in range(number):
    digit=input('Enter your digit: ')
    a_list.append(digit)
print(a_list)
for j in a_list:
    if j=='10':
        num1+=1
    elif j=='20':
        num2+=1
    elif j=='30':
        num3+=1
    elif j=='STOP':
        pass
    elif j=='50':
        num4+=1
    else:
        num5+=1
print('10 -', num1, 'times')
print('20 -', num2, 'times')
print('30 -', num3, 'times')
print('50 -', num4, 'times')
print('90 -', num5, 'times')

li=[]
count=0
new_li=[]

while True:
  n=input("Enter your values: ").upper()
  if n=="STOP":
      break
  else:
      li.append(int(n))

for x in range(len(li)):
    if li[x] not in new_li:
         new_li.append(li[x])

for x in new_li:
    result=li.count(x)
    print(x,"-",result,"times")

#task-2:
a_list=int(input('Sir, please enter your desired digit: '))
b_list=[]
for i in range(a_list):
    word=input('Sir, please enter your word: ')
    b_list.append(word.split(' '))
print(b_list)
sum=0
res=0
trgt=None
for itm in b_list:
    for num in itm:
        res+=int(num)
    if res>sum:
        sum=res
        trgt=itm
    res=0
print(sum)
print(trgt)



"""Dictionary & Tuple:"""

dict1={'a': 100, 'b': 100, 'c': 200, 'd': 300}
dict2={'a': 300, 'b': 200, 'd': 400, 'e': 200}
dict3={}

for k,v in dict1.items():
    if k not in dict3:
        dict3[k]=v

for k1, v1 in dict2.items():
    if k1 in dict3:
        dict3[k1] = v1 + dict3[k1]
    elif k1 not in dict3:
        dict3[k1]=v1


print(dict3)
a_list=[]
for key,value in dict3.items():
    a_list.append(value)
print(a_list)
b_list=[]
b_list=sorted(a_list)
print(b_list)
new_list=[]
for k in b_list:
    if k not in new_list:
        new_list.append(k)
print(tuple(new_list))

#task-3:
a_dict={'key1' : 'value1', 'key2' : 'value2', 'key3' : 'value1'}
b_dict={}
list1=[]
for key,value in a_dict.items():
    if value==value1:
        list1.append(key)
print(list1)